name: publish
on:
  push:
    tags:
    - '*'
  workflow_dispatch:
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Execute Targets: Publish'
      run: dotnet run --verbosity q --project ./src/build/build.csproj -- Publish --plan --from-ref HEAD~1 --to-ref HEAD --nuget-api-key ${{ secrets.NUGET_API_KEY }} --github-token ${{ secrets.GITHUB_TOKEN }}